# Generated by Django 3.0.8 on 2020-08-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('Altitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('Speed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Direction', models.IntegerField()),
            ],
        ),
    ]
