# Generated by Django 3.0.8 on 2020-08-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputloc',
            name='Endurance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='inputloc',
            name='Latitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inputloc',
            name='Longitude',
            field=models.TextField(),
        ),
    ]
