# Generated by Django 3.0.8 on 2020-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_map', '0003_inputloc_search_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFacitily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='inputloc',
            name='Altitude',
        ),
        migrations.RemoveField(
            model_name='inputloc',
            name='Direction',
        ),
        migrations.RemoveField(
            model_name='inputloc',
            name='Endurance',
        ),
        migrations.RemoveField(
            model_name='inputloc',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='inputloc',
            name='Longitude',
        ),
        migrations.RemoveField(
            model_name='inputloc',
            name='Speed',
        ),
        migrations.AddField(
            model_name='inputloc',
            name='altitude',
            field=models.FloatField(default=0.0, help_text='Enter Altitude in feets'),
        ),
        migrations.AddField(
            model_name='inputloc',
            name='direction',
            field=models.FloatField(default=0.0, help_text='Enter Direction in Degrees'),
        ),
        migrations.AddField(
            model_name='inputloc',
            name='divergence',
            field=models.FloatField(default=0.0, help_text='Enter Divergence in Degrees'),
        ),
        migrations.AddField(
            model_name='inputloc',
            name='endurance',
            field=models.FloatField(default=0.0, help_text='Enter Endurance in hours'),
        ),
        migrations.AddField(
            model_name='inputloc',
            name='latitude',
            field=models.FloatField(default=0.0, help_text='Enter Latitude in Degrees'),
        ),
        migrations.AddField(
            model_name='inputloc',
            name='longitude',
            field=models.FloatField(default=0.0, help_text='Enter Longitude in Degrees'),
        ),
        migrations.AddField(
            model_name='inputloc',
            name='speed',
            field=models.FloatField(default=0.0, help_text='Enter Speed in knots'),
        ),
    ]
