# Generated by Django 3.0.8 on 2020-09-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_map', '0004_auto_20200903_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchFacitily',
            new_name='SearchFacility',
        ),
    ]
